PROGRAM T23;
BEGIN
  WRITELN(LENGTH('HELLO'));
  WRITELN(LENGTH(''));
  WRITELN(POS('LL', 'HELLO'));
  WRITELN(POS('X', 'HELLO'));
  WRITELN(POS('HE', 'HELLO'));
  WRITELN(COPY('HELLO WORLD', 7, 5));
  WRITELN(COPY('HELLO', 1, 3));
  WRITELN(COPY('HELLO', 4, 99));
  WRITELN(CONCAT('FOO', 'BAR'));
  WRITELN(CONCAT('A', 'B', 'C', 'D'));
  WRITELN(CONCAT('HE', COPY('HELLO', 3, 3)))
END.
