PROGRAM T24;
VAR
  F: TEXT;
  C: CHAR;
  N: INTEGER;
BEGIN
  ASSIGN(F, 'TEST.TXT');
  REWRITE(F);
  WRITELN(F, 'HELLO FILE');
  WRITELN(F, 42);
  WRITE(F, 'NO');
  WRITE(F, 'NEWLINE');
  WRITELN(F);
  WRITELN(F, 1234);
  CLOSE(F);

  ASSIGN(F, 'TEST.TXT');
  RESET(F);
  WHILE NOT EOF(F) DO BEGIN
    READ(F, C);
    WRITE(C)
  END;
  CLOSE(F);

  ASSIGN(F, 'TEST.TXT');
  RESET(F);
  READLN(F);
  READLN(F, N);
  WRITELN('GOT N=', N);
  CLOSE(F)
END.
