PROGRAM T25;
VAR
  F: TEXT;
  S: STRING;
  B: BOOLEAN;
  N: INTEGER;
BEGIN
  ASSIGN(F, 'T25.TXT');
  REWRITE(F);
  WRITELN(F, 'FIRST LINE');
  WRITELN(F, 'SECOND LINE WITH SPACES');
  WRITE(F, 'BOOL=');
  WRITELN(F, TRUE);
  WRITE(F, 'BOOL=');
  WRITELN(F, FALSE);
  WRITELN(F, 99);
  CLOSE(F);

  ASSIGN(F, 'T25.TXT');
  RESET(F);
  WHILE NOT EOF(F) DO BEGIN
    READ(F, S);
    READLN(F);
    WRITE('GOT: ');
    WRITELN(S)
  END;
  CLOSE(F);

  ASSIGN(F, 'T25.TXT');
  RESET(F);
  READLN(F);
  READLN(F);
  READLN(F);
  READLN(F);
  WRITELN('EOLN BEFORE INT: ', EOLN(F));
  READ(F, N);
  WRITELN('READ INT: ', N);
  WRITELN('EOLN AFTER INT: ', EOLN(F));
  CLOSE(F)
END.
