PROGRAM T27H;
TYPE
  TPOINT = RECORD X, Y: INTEGER END;
  TLINE = RECORD A, B: TPOINT END;
  TBOX  = RECORD
            HEAD: TLINE;
            TAIL: RECORD U, V: INTEGER END
          END;
VAR
  L: TLINE;
  K: TBOX;
BEGIN
  L.A.X := 1;
  L.B.X := 30;
  WRITELN(L.A.X);
  WRITELN(L.B.X);
  K.HEAD.A.X := 100;
  K.HEAD.B.X := 300;
  WRITELN(K.HEAD.A.X);
  WRITELN(K.HEAD.B.X)
END.
