PROGRAM T27J;
TYPE
  TPOINT = RECORD X, Y: INTEGER END;
  TLINE = RECORD A, B: TPOINT END;
  TBOX  = RECORD
            HEAD: TLINE;
            TAIL: RECORD U, V: INTEGER END
          END;
VAR
  K: TBOX;
BEGIN
  K.TAIL.U := 555;
  WRITELN(K.TAIL.U)
END.
