PROGRAM T33A;

FUNCTION TWICE(R: REAL): REAL;
BEGIN
  TWICE := R + R
END;

FUNCTION BUMP(I: INTEGER; R: REAL): REAL;
BEGIN
  IF R > I THEN
    BUMP := R - I
  ELSE
    BUMP := I - R
END;

BEGIN
  WRITELN(TWICE(1.25));
  WRITELN(BUMP(2, 3.50));
  WRITELN(BUMP(5, 2.50));
  WRITELN(TWICE(2))
END.
