;
; File generated by cc65 v 2.19 - Git 128b15a71
;
	.fopt		compiler,"cc65 v 2.19 - Git 128b15a71"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cputc
	.import		_cputs
	.import		_cprintf
	.import		_cgetc
	.import		_strtok
	.import		_malloc
	.import		_sscanf
	.import		_readrtc
	.import		_writertc
	.export		_dectobcd
	.export		_bcdtodec
	.export		_UpdateTime
	.export		_UpdateDate
	.export		_UpdateConsole
	.export		_UpdateDsky
	.export		_PrintConsoleType
	.export		_PrintDskyType
	.export		_cgets
	.export		_main

.segment	"RODATA"

S0006:
	.byte	$0A,$0D,$77,$6F,$75,$6C,$64,$20,$79,$6F,$75,$20,$6C,$69,$6B,$65
	.byte	$20,$74,$6F,$20,$63,$68,$61,$6E,$67,$65,$20,$74,$68,$65,$20,$73
	.byte	$79,$73,$74,$65,$6D,$20,$43,$6F,$6E,$73,$6F,$6C,$65,$3F,$20,$28
	.byte	$79,$2F,$4E,$29,$00
S0002:
	.byte	$43,$75,$72,$72,$65,$6E,$74,$20,$53,$79,$73,$74,$65,$6D,$20,$74
	.byte	$69,$6D,$65,$20,$69,$73,$20,$25,$69,$3A,$25,$30,$32,$69,$3A,$25
	.byte	$30,$32,$69,$20,$25,$63,$4D,$20,$25,$69,$2F,$25,$69,$2F,$25,$30
	.byte	$32,$69,$0A,$0D,$00
S0009:
	.byte	$0A,$0D,$77,$6F,$75,$6C,$64,$20,$79,$6F,$75,$20,$6C,$69,$6B,$65
	.byte	$20,$74,$6F,$20,$63,$68,$61,$6E,$67,$65,$20,$74,$68,$65,$20,$44
	.byte	$53,$4B,$59,$20,$73,$65,$74,$74,$69,$6E,$67,$73,$3F,$20,$28,$79
	.byte	$2F,$4E,$29,$00
S0003:
	.byte	$77,$6F,$75,$6C,$64,$20,$79,$6F,$75,$20,$6C,$69,$6B,$65,$20,$74
	.byte	$6F,$20,$63,$68,$61,$6E,$67,$65,$20,$74,$68,$65,$20,$73,$79,$73
	.byte	$74,$65,$6D,$20,$74,$69,$6D,$65,$3F,$20,$28,$79,$2F,$4E,$29,$00
S0014:
	.byte	$0A,$0D,$43,$68,$61,$6E,$67,$65,$20,$74,$6F,$3A,$20,$25,$32,$64
	.byte	$3A,$25,$30,$32,$64,$3A,$25,$30,$32,$64,$20,$25,$63,$4D,$3F,$20
	.byte	$28,$79,$2F,$4E,$29,$0A,$0D,$00
S0029:
	.byte	$53,$65,$74,$20,$44,$53,$4B,$59,$20,$74,$6F,$20,$4E,$65,$78,$74
	.byte	$20,$47,$65,$6E,$65,$72,$61,$74,$69,$6F,$6E,$20,$44,$53,$4B,$59
	.byte	$0A,$0D,$00
S001C:
	.byte	$0A,$0D,$43,$68,$61,$6E,$67,$65,$20,$74,$6F,$3A,$20,$25,$64,$2F
	.byte	$25,$64,$2F,$25,$30,$32,$64,$20,$28,$79,$2F,$4E,$29,$0A,$0D,$00
S0005:
	.byte	$43,$6F,$6E,$73,$6F,$6C,$65,$20,$69,$73,$20,$63,$75,$72,$72,$65
	.byte	$6E,$74,$6C,$79,$20,$73,$65,$74,$20,$74,$6F,$3A,$00
S0026:
	.byte	$33,$20,$2D,$3E,$20,$4E,$65,$78,$74,$20,$47,$65,$6E,$65,$72,$61
	.byte	$74,$69,$6F,$6E,$20,$44,$53,$4B,$59,$0A,$0D,$00
S0028:
	.byte	$53,$65,$74,$20,$44,$53,$4B,$59,$20,$74,$6F,$20,$6F,$72,$69,$67
	.byte	$69,$6E,$61,$6C,$20,$44,$53,$4B,$59,$0A,$0D,$00
S000B:
	.byte	$45,$6E,$74,$65,$72,$20,$54,$69,$6D,$65,$20,$28,$48,$48,$3A,$4D
	.byte	$4D,$3A,$53,$53,$20,$41,$2F,$50,$29,$3A,$20,$00
S0021:
	.byte	$53,$65,$74,$20,$74,$6F,$20,$49,$6E,$74,$65,$72,$6E,$61,$6C,$20
	.byte	$43,$6F,$6E,$73,$6F,$6C,$65,$0A,$0D,$00
S0008:
	.byte	$44,$53,$4B,$59,$20,$69,$73,$20,$63,$75,$72,$72,$65,$6E,$74,$6C
	.byte	$79,$20,$73,$65,$74,$20,$74,$6F,$3A,$00
S0001:
	.byte	$0A,$0D,$36,$78,$30,$78,$20,$4E,$56,$52,$41,$4D,$20,$55,$74,$69
	.byte	$6C,$69,$74,$79,$0A,$0D,$0A,$0D,$00
S0015:
	.byte	$45,$6E,$74,$65,$72,$20,$44,$61,$74,$65,$20,$28,$4D,$4D,$2F,$44
	.byte	$44,$2F,$59,$59,$29,$3A,$20,$00
S001E:
	.byte	$31,$20,$2D,$3E,$20,$49,$6E,$74,$65,$72,$6E,$61,$6C,$20,$43,$6F
	.byte	$6E,$73,$6F,$6C,$65,$0A,$0D,$00
S0020:
	.byte	$53,$65,$74,$20,$74,$6F,$20,$53,$65,$72,$69,$61,$6C,$20,$50,$6F
	.byte	$72,$74,$20,$31,$0A,$0D,$00
S001F:
	.byte	$32,$20,$2D,$3E,$20,$53,$65,$72,$69,$61,$6C,$20,$50,$6F,$72,$74
	.byte	$20,$31,$0A,$0D,$00
S0025:
	.byte	$32,$20,$2D,$3E,$20,$4F,$72,$69,$67,$69,$6E,$61,$6C,$20,$44,$53
	.byte	$4B,$59,$0A,$0D,$00
S0027:
	.byte	$53,$65,$74,$20,$44,$53,$4B,$59,$20,$74,$6F,$20,$6E,$6F,$6E,$65
	.byte	$0A,$0D,$00
S0030:
	.byte	$4E,$65,$78,$74,$20,$47,$65,$6E,$65,$72,$61,$74,$69,$6F,$6E,$00
S002B:
	.byte	$53,$45,$52,$49,$41,$4C,$20,$50,$4F,$52,$54,$20,$31,$00
S0024:
	.byte	$31,$20,$2D,$3E,$20,$4E,$6F,$6E,$65,$0A,$0D,$00
S0023:
	.byte	$53,$65,$6C,$65,$63,$74,$3A,$0A,$0D,$00
S001D	:=	S0023+0
S002F:
	.byte	$4F,$72,$69,$67,$69,$6E,$61,$6C,$00
S002C:
	.byte	$49,$4E,$54,$45,$52,$4E,$41,$4C,$00
S002D:
	.byte	$55,$4E,$4B,$4E,$4F,$57,$4E,$00
S0031	:=	S002D+0
S002E:
	.byte	$4E,$4F,$4E,$45,$00
S002A	:=	S0002+50
S0013:
	.byte	$25,$63,$00
S0022	:=	S0002+50
S0017:
	.byte	$25,$64,$00
S0011	:=	S0017+0
S001B	:=	S0017+0
S000D	:=	S0017+0
S000A	:=	S0002+50
S0019	:=	S0017+0
S0004	:=	S0002+50
S000F	:=	S0017+0
S0007	:=	S0002+50
S000E	:=	S0005+27
S001A	:=	S000B+26
S0010	:=	S000B+26
S0018:
	.byte	$2F,$00
S000C	:=	S0005+27
S0016	:=	S0018+0
S0012	:=	S0006+52

; ---------------------------------------------------------------
; unsigned char __near__ dectobcd (unsigned char in)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_dectobcd: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp,x)
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	jsr     aslax4
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	jsr     mulax10
	jsr     tossubax
	jsr     tosaddax
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bcdtodec (unsigned char in)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bcdtodec: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	and     #$0F
	sta     sreg
	lda     (sp),y
	ldx     #$00
	and     #$F0
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	jsr     mulax10
	clc
	adc     sreg
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateTime (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateTime: near

.segment	"CODE"

	ldy     #$0D
	jsr     subysp
	ldx     #$00
	lda     #$50
	jsr     _malloc
	ldy     #$0B
	jsr     staxysp
	lda     #<(S000B)
	ldx     #>(S000B)
	jsr     _cputs
	ldy     #$0E
	jsr     pushwysp
	ldx     #$00
	lda     #$4F
	jsr     _cgets
	ldy     #$0E
	jsr     pushwysp
	lda     #<(S000C)
	ldx     #>(S000C)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(S000D)
	ldx     #>(S000D)
	jsr     pushax
	lda     #$0B
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(S000E)
	ldx     #>(S000E)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(S000F)
	ldx     #>(S000F)
	jsr     pushax
	lda     #$09
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(S0010)
	ldx     #>(S0010)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(S0011)
	ldx     #>(S0011)
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(S0012)
	ldx     #>(S0012)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(S0013)
	ldx     #>(S0013)
	jsr     pushax
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	ldy     #$02
	lda     (sp),y
	bne     L0017
	dey
	lda     (sp),y
	cmp     #$70
	beq     L0004
	iny
L0017:	lda     (sp),y
	bne     L0015
	dey
	lda     (sp),y
	cmp     #$50
	beq     L0004
L0015:	ldx     #$00
	jmp     L0012
L0004:	ldx     #$00
	lda     #$50
	jmp     L0018
L0012:	lda     #$41
	ldy     #$01
L0018:	jsr     staxysp
	lda     #<(S0014)
	ldx     #>(S0014)
	jsr     pushax
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0A
	jsr     _cprintf
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$79
	beq     L0013
	lda     (sp),y
	cmp     #$59
	bne     L0008
L0013:	ldy     #$02
	lda     (sp),y
	bne     L000B
	dey
	lda     (sp),y
	cmp     #$50
	bne     L000B
	ldy     #$08
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	ldy     #$07
	jsr     staxysp
L000B:	ldy     #$08
	lda     (sp),y
	bne     L0019
	dey
	lda     (sp),y
	cmp     #$0C
	bne     L000D
	ldx     #$00
	txa
	jsr     staxysp
L000D:	ldy     #$08
L0019:	lda     (sp),y
	bne     L000F
	dey
	lda     (sp),y
	cmp     #$18
	bne     L000F
	ldx     #$00
	lda     #$0C
	jsr     staxysp
L000F:	lda     #$00
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$01
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$02
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
L0008:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateDate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDate: near

.segment	"CODE"

	ldy     #$0B
	jsr     subysp
	ldx     #$00
	lda     #$50
	jsr     _malloc
	ldy     #$09
	jsr     staxysp
	lda     #<(S0015)
	ldx     #>(S0015)
	jsr     _cputs
	ldy     #$0C
	jsr     pushwysp
	ldx     #$00
	lda     #$4F
	jsr     _cgets
	ldy     #$0C
	jsr     pushwysp
	lda     #<(S0016)
	ldx     #>(S0016)
	jsr     _strtok
	ldy     #$07
	jsr     staxysp
	jsr     pushax
	lda     #<(S0017)
	ldx     #>(S0017)
	jsr     pushax
	lda     #$09
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(S0018)
	ldx     #>(S0018)
	jsr     _strtok
	ldy     #$07
	jsr     staxysp
	jsr     pushax
	lda     #<(S0019)
	ldx     #>(S0019)
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(S001A)
	ldx     #>(S001A)
	jsr     _strtok
	ldy     #$07
	jsr     staxysp
	jsr     pushax
	lda     #<(S001B)
	ldx     #>(S001B)
	jsr     pushax
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	lda     #<(S001C)
	ldx     #>(S001C)
	jsr     pushax
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$08
	jsr     _cprintf
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$79
	beq     L0005
	lda     (sp),y
	cmp     #$59
	bne     L0002
L0005:	lda     #$03
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$04
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$06
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
L0002:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateConsole (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateConsole: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(S001D)
	ldx     #>(S001D)
	jsr     _cputs
	lda     #<(S001E)
	ldx     #>(S001E)
	jsr     _cputs
	lda     #<(S001F)
	ldx     #>(S001F)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$32
	bne     L0005
	lda     #$21
	jsr     pusha
	lda     #$04
	jsr     _writertc
	lda     #<(S0020)
	ldx     #>(S0020)
	jmp     L0004
L0005:	lda     #$21
	jsr     pusha
	lda     #$09
	jsr     _writertc
	lda     #<(S0021)
	ldx     #>(S0021)
L0004:	jsr     _cputs
	lda     #<(S0022)
	ldx     #>(S0022)
	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateDsky (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDsky: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(S0023)
	ldx     #>(S0023)
	jsr     _cputs
	lda     #<(S0024)
	ldx     #>(S0024)
	jsr     _cputs
	lda     #<(S0025)
	ldx     #>(S0025)
	jsr     _cputs
	lda     #<(S0026)
	ldx     #>(S0026)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$31
	bne     L0006
	lda     #$22
	jsr     pusha
	lda     #$00
	jsr     _writertc
	lda     #<(S0027)
	ldx     #>(S0027)
	jsr     _cputs
	ldy     #$00
L0006:	lda     (sp),y
	cmp     #$32
	bne     L0008
	lda     #$22
	jsr     pusha
	lda     #$01
	jsr     _writertc
	lda     #<(S0028)
	ldx     #>(S0028)
	jsr     _cputs
	ldy     #$00
L0008:	lda     (sp),y
	cmp     #$33
	bne     L0004
	lda     #$22
	jsr     pusha
	lda     #$02
	jsr     _writertc
	lda     #<(S0029)
	ldx     #>(S0029)
	jsr     _cputs
L0004:	lda     #<(S002A)
	ldx     #>(S002A)
	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ PrintConsoleType (unsigned char in)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_PrintConsoleType: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	cmp     #$04
	beq     L0004
	cmp     #$09
	beq     L0005
	jmp     L0006
L0004:	lda     #<(S002B)
	ldx     #>(S002B)
	jmp     L0007
L0005:	lda     #<(S002C)
	ldx     #>(S002C)
	jmp     L0007
L0006:	lda     #<(S002D)
	ldx     #>(S002D)
L0007:	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ PrintDskyType (unsigned char in)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_PrintDskyType: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	beq     L0004
	cmp     #$01
	beq     L0005
	cmp     #$02
	beq     L0006
	jmp     L0007
L0004:	lda     #<(S002E)
	ldx     #>(S002E)
	jmp     L0008
L0005:	lda     #<(S002F)
	ldx     #>(S002F)
	jmp     L0008
L0006:	lda     #<(S0030)
	ldx     #>(S0030)
	jmp     L0008
L0007:	lda     #<(S0031)
	ldx     #>(S0031)
L0008:	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ cgets (char *buffer, int length)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cgets: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	tax
	lda     #$01
	ldy     #$03
	jsr     subeqysp
	ldy     #$04
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0003
	eor     #$80
L0003:	jpl     L0005
	jmp     L000F
L0004:	jsr     _cgetc
	ldy     #$02
	sta     (sp),y
	cmp     #$08
	bne     L001A
	ldy     #$00
	lda     (sp),y
	beq     L0007
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
	lda     #$20
	jsr     _cputc
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
L0007:	ldy     #$02
L001A:	lda     (sp),y
	cmp     #$20
	bcc     L000B
	cmp     #$7F
	bcs     L000B
	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
L000B:	ldy     #$04
	jsr     ldaxysp
	ldy     #$00
	cmp     (sp),y
	bne     L0019
	txa
	beq     L001C
L0019:	ldy     #$02
	lda     (sp),y
	cmp     #$0D
	bne     L000F
	ldx     #$00
L001C:	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	txa
	iny
	sta     (sp),y
L000F:	ldy     #$01
	lda     (sp),y
	jne     L0004
L0005:	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp6
	lda     #$41
	jsr     pusha
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _cputs
	lda     #$07
	jsr     pusha
	lda     #$00
	jsr     _writertc
	lda     #$08
	jsr     pusha
	lda     #$A5
	jsr     _writertc
	lda     #$00
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$01
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$02
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$03
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$05
	sta     (sp),y
	lda     #$04
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$06
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$04
	sta     (sp),y
	lda     #$20
	jsr     pusha
	lda     #$A5
	jsr     _writertc
	ldy     #$03
	lda     (sp),y
	cmp     #$0C
	bcc     L000F
	lda     #$50
	ldy     #$00
	sta     (sp),y
	ldy     #$03
	lda     (sp),y
	cmp     #$0D
	bcc     L000F
	ldx     #$00
	lda     (sp),y
	ldy     #$0C
	jsr     decaxy
	ldy     #$03
	sta     (sp),y
L000F:	lda     (sp),y
	bne     L0004
	lda     #$0C
	sta     (sp),y
L0004:	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	lda     (sp),y
	jsr     pusha0
	ldy     #$10
	lda     (sp),y
	jsr     pusha0
	ldy     #$11
	lda     (sp),y
	jsr     pusha0
	ldy     #$12
	lda     (sp),y
	jsr     pusha0
	ldy     #$10
	jsr     _cprintf
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$07
	sta     (sp),y
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     _cputs
	ldy     #$07
	lda     (sp),y
	cmp     #$79
	beq     L0010
	cmp     #$59
	bne     L0005
L0010:	jsr     _UpdateTime
	jsr     _UpdateDate
L0005:	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     _cputs
	lda     #$21
	jsr     _readrtc
	jsr     _PrintConsoleType
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$07
	sta     (sp),y
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     _cputs
	ldy     #$07
	lda     (sp),y
	cmp     #$79
	beq     L0011
	cmp     #$59
	bne     L0008
L0011:	jsr     _UpdateConsole
L0008:	lda     #<(S0008)
	ldx     #>(S0008)
	jsr     _cputs
	lda     #$22
	jsr     _readrtc
	jsr     _PrintDskyType
	lda     #<(S0009)
	ldx     #>(S0009)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$07
	sta     (sp),y
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _cputs
	ldy     #$07
	lda     (sp),y
	cmp     #$79
	beq     L0012
	cmp     #$59
	bne     L0013
L0012:	jsr     _UpdateDsky
L0013:	lda     #$07
	jsr     pusha
	lda     #$80
	jsr     _writertc
	ldx     #$00
	txa
	jmp     incsp8

.endproc

