;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cputc
	.import		_cputs
	.import		_cprintf
	.import		_cgetc
	.import		_strtok
	.import		_malloc
	.import		_sscanf
	.import		_readrtc
	.import		_writertc
	.export		_dectobcd
	.export		_bcdtodec
	.export		_UpdateTime
	.export		_UpdateDate
	.export		_UpdateConsole
	.export		_UpdateDsky
	.export		_PrintConsoleType
	.export		_PrintDskyType
	.export		_cgets
	.export		_main

.segment	"RODATA"

L0054:
	.byte	$0A,$0D,$77,$6F,$75,$6C,$64,$20,$79,$6F,$75,$20,$6C,$69,$6B,$65
	.byte	$20,$74,$6F,$20,$63,$68,$61,$6E,$67,$65,$20,$74,$68,$65,$20,$73
	.byte	$79,$73,$74,$65,$6D,$20,$43,$6F,$6E,$73,$6F,$6C,$65,$3F,$20,$28
	.byte	$79,$2F,$4E,$29,$00
L0035:
	.byte	$43,$75,$72,$72,$65,$6E,$74,$20,$53,$79,$73,$74,$65,$6D,$20,$74
	.byte	$69,$6D,$65,$20,$69,$73,$20,$25,$69,$3A,$25,$30,$32,$69,$3A,$25
	.byte	$30,$32,$69,$20,$25,$63,$4D,$20,$25,$69,$2F,$25,$69,$2F,$25,$30
	.byte	$32,$69,$0A,$0D,$00
L0068:
	.byte	$0A,$0D,$77,$6F,$75,$6C,$64,$20,$79,$6F,$75,$20,$6C,$69,$6B,$65
	.byte	$20,$74,$6F,$20,$63,$68,$61,$6E,$67,$65,$20,$74,$68,$65,$20,$44
	.byte	$53,$4B,$59,$20,$73,$65,$74,$74,$69,$6E,$67,$73,$3F,$20,$28,$79
	.byte	$2F,$4E,$29,$00
L003F:
	.byte	$77,$6F,$75,$6C,$64,$20,$79,$6F,$75,$20,$6C,$69,$6B,$65,$20,$74
	.byte	$6F,$20,$63,$68,$61,$6E,$67,$65,$20,$74,$68,$65,$20,$73,$79,$73
	.byte	$74,$65,$6D,$20,$74,$69,$6D,$65,$3F,$20,$28,$79,$2F,$4E,$29,$00
L00C5:
	.byte	$0A,$0D,$43,$68,$61,$6E,$67,$65,$20,$74,$6F,$3A,$20,$25,$32,$64
	.byte	$3A,$25,$30,$32,$64,$3A,$25,$30,$32,$64,$20,$25,$63,$4D,$3F,$20
	.byte	$28,$79,$2F,$4E,$29,$0A,$0D,$00
L0171:
	.byte	$53,$65,$74,$20,$44,$53,$4B,$59,$20,$74,$6F,$20,$4E,$65,$78,$74
	.byte	$20,$47,$65,$6E,$65,$72,$61,$74,$69,$6F,$6E,$20,$44,$53,$4B,$59
	.byte	$0A,$0D,$00
L0116:
	.byte	$0A,$0D,$43,$68,$61,$6E,$67,$65,$20,$74,$6F,$3A,$20,$25,$64,$2F
	.byte	$25,$64,$2F,$25,$30,$32,$64,$20,$28,$79,$2F,$4E,$29,$0A,$0D,$00
L004E:
	.byte	$43,$6F,$6E,$73,$6F,$6C,$65,$20,$69,$73,$20,$63,$75,$72,$72,$65
	.byte	$6E,$74,$6C,$79,$20,$73,$65,$74,$20,$74,$6F,$3A,$00
L0157:
	.byte	$33,$20,$2D,$3E,$20,$4E,$65,$78,$74,$20,$47,$65,$6E,$65,$72,$61
	.byte	$74,$69,$6F,$6E,$20,$44,$53,$4B,$59,$0A,$0D,$00
L0169:
	.byte	$53,$65,$74,$20,$44,$53,$4B,$59,$20,$74,$6F,$20,$6F,$72,$69,$67
	.byte	$69,$6E,$61,$6C,$20,$44,$53,$4B,$59,$0A,$0D,$00
L008B:
	.byte	$45,$6E,$74,$65,$72,$20,$54,$69,$6D,$65,$20,$28,$48,$48,$3A,$4D
	.byte	$4D,$3A,$53,$53,$20,$41,$2F,$50,$29,$3A,$20,$00
L0147:
	.byte	$53,$65,$74,$20,$74,$6F,$20,$49,$6E,$74,$65,$72,$6E,$61,$6C,$20
	.byte	$43,$6F,$6E,$73,$6F,$6C,$65,$0A,$0D,$00
L0062:
	.byte	$44,$53,$4B,$59,$20,$69,$73,$20,$63,$75,$72,$72,$65,$6E,$74,$6C
	.byte	$79,$20,$73,$65,$74,$20,$74,$6F,$3A,$00
L0005:
	.byte	$0A,$0D,$36,$78,$30,$78,$20,$4E,$56,$52,$41,$4D,$20,$55,$74,$69
	.byte	$6C,$69,$74,$79,$0A,$0D,$0A,$0D,$00
L00F2:
	.byte	$45,$6E,$74,$65,$72,$20,$44,$61,$74,$65,$20,$28,$4D,$4D,$2F,$44
	.byte	$44,$2F,$59,$59,$29,$3A,$20,$00
L0133:
	.byte	$31,$20,$2D,$3E,$20,$49,$6E,$74,$65,$72,$6E,$61,$6C,$20,$43,$6F
	.byte	$6E,$73,$6F,$6C,$65,$0A,$0D,$00
L0140:
	.byte	$53,$65,$74,$20,$74,$6F,$20,$53,$65,$72,$69,$61,$6C,$20,$50,$6F
	.byte	$72,$74,$20,$31,$0A,$0D,$00
L0136:
	.byte	$32,$20,$2D,$3E,$20,$53,$65,$72,$69,$61,$6C,$20,$50,$6F,$72,$74
	.byte	$20,$31,$0A,$0D,$00
L0154:
	.byte	$32,$20,$2D,$3E,$20,$4F,$72,$69,$67,$69,$6E,$61,$6C,$20,$44,$53
	.byte	$4B,$59,$0A,$0D,$00
L0161:
	.byte	$53,$65,$74,$20,$44,$53,$4B,$59,$20,$74,$6F,$20,$6E,$6F,$6E,$65
	.byte	$0A,$0D,$00
L0199:
	.byte	$4E,$65,$78,$74,$20,$47,$65,$6E,$65,$72,$61,$74,$69,$6F,$6E,$00
L017D:
	.byte	$53,$45,$52,$49,$41,$4C,$20,$50,$4F,$52,$54,$20,$31,$00
L0151:
	.byte	$31,$20,$2D,$3E,$20,$4E,$6F,$6E,$65,$0A,$0D,$00
L014E:
	.byte	$53,$65,$6C,$65,$63,$74,$3A,$0A,$0D,$00
L0130	:=	L014E+0
L0194:
	.byte	$4F,$72,$69,$67,$69,$6E,$61,$6C,$00
L0182:
	.byte	$49,$4E,$54,$45,$52,$4E,$41,$4C,$00
L0186:
	.byte	$55,$4E,$4B,$4E,$4F,$57,$4E,$00
L019D	:=	L0186+0
L018F:
	.byte	$4E,$4F,$4E,$45,$00
L0174	:=	L0035+50
L00B5:
	.byte	$25,$63,$00
L014A	:=	L0035+50
L00FE:
	.byte	$25,$64,$00
L00AB	:=	L00FE+0
L0112	:=	L00FE+0
L0097	:=	L00FE+0
L006D	:=	L0035+50
L0108	:=	L00FE+0
L0044	:=	L0035+50
L00A1	:=	L00FE+0
L0059	:=	L0035+50
L009D	:=	L004E+27
L010E	:=	L008B+26
L00A7	:=	L008B+26
L0104:
	.byte	$2F,$00
L0093	:=	L004E+27
L00FA	:=	L0104+0
L00B1	:=	L0054+52

; ---------------------------------------------------------------
; unsigned char __near__ dectobcd (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_dectobcd: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp,x)
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	jsr     shlax4
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	jsr     mulax10
	jsr     tossubax
	jsr     tosaddax
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bcdtodec (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bcdtodec: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	and     #$0F
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	and     #$F0
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	jsr     mulax10
	jsr     tosaddax
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateTime (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateTime: near

.segment	"CODE"

	ldy     #$0D
	jsr     subysp
	ldx     #$00
	lda     #$50
	jsr     _malloc
	ldy     #$0B
	jsr     staxysp
	lda     #<(L008B)
	ldx     #>(L008B)
	jsr     _cputs
	ldy     #$0E
	jsr     pushwysp
	ldx     #$00
	lda     #$4F
	jsr     _cgets
	ldy     #$0E
	jsr     pushwysp
	lda     #<(L0093)
	ldx     #>(L0093)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(L0097)
	ldx     #>(L0097)
	jsr     pushax
	lda     #$0B
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(L009D)
	ldx     #>(L009D)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(L00A1)
	ldx     #>(L00A1)
	jsr     pushax
	lda     #$09
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(L00A7)
	ldx     #>(L00A7)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(L00AB)
	ldx     #>(L00AB)
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(L00B1)
	ldx     #>(L00B1)
	jsr     _strtok
	ldy     #$09
	jsr     staxysp
	jsr     pushax
	lda     #<(L00B5)
	ldx     #>(L00B5)
	jsr     pushax
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	ldy     #$02
	lda     (sp),y
	bne     L01DA
	dey
	lda     (sp),y
	cmp     #$70
	beq     L00B9
	iny
L01DA:	lda     (sp),y
	bne     L01D8
	dey
	lda     (sp),y
	cmp     #$50
	beq     L00B9
L01D8:	ldx     #$00
	jmp     L01D5
L00B9:	ldx     #$00
	lda     #$50
	jmp     L01DB
L01D5:	lda     #$41
	ldy     #$01
L01DB:	jsr     staxysp
	lda     #<(L00C5)
	ldx     #>(L00C5)
	jsr     pushax
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$0A
	jsr     _cprintf
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$79
	beq     L01D6
	lda     (sp),y
	cmp     #$59
	bne     L00CD
L01D6:	ldy     #$02
	lda     (sp),y
	bne     L00D2
	dey
	lda     (sp),y
	cmp     #$50
	bne     L00D2
	ldy     #$08
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	ldy     #$07
	jsr     staxysp
L00D2:	ldy     #$08
	lda     (sp),y
	bne     L01DC
	dey
	lda     (sp),y
	cmp     #$0C
	bne     L00D7
	ldx     #$00
	txa
	jsr     staxysp
L00D7:	ldy     #$08
L01DC:	lda     (sp),y
	bne     L00DC
	dey
	lda     (sp),y
	cmp     #$18
	bne     L00DC
	ldx     #$00
	lda     #$0C
	jsr     staxysp
L00DC:	lda     #$00
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$01
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$02
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
L00CD:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateDate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDate: near

.segment	"CODE"

	ldy     #$0B
	jsr     subysp
	ldx     #$00
	lda     #$50
	jsr     _malloc
	ldy     #$09
	jsr     staxysp
	lda     #<(L00F2)
	ldx     #>(L00F2)
	jsr     _cputs
	ldy     #$0C
	jsr     pushwysp
	ldx     #$00
	lda     #$4F
	jsr     _cgets
	ldy     #$0C
	jsr     pushwysp
	lda     #<(L00FA)
	ldx     #>(L00FA)
	jsr     _strtok
	ldy     #$07
	jsr     staxysp
	jsr     pushax
	lda     #<(L00FE)
	ldx     #>(L00FE)
	jsr     pushax
	lda     #$09
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(L0104)
	ldx     #>(L0104)
	jsr     _strtok
	ldy     #$07
	jsr     staxysp
	jsr     pushax
	lda     #<(L0108)
	ldx     #>(L0108)
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	jsr     push0
	lda     #<(L010E)
	ldx     #>(L010E)
	jsr     _strtok
	ldy     #$07
	jsr     staxysp
	jsr     pushax
	lda     #<(L0112)
	ldx     #>(L0112)
	jsr     pushax
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	ldy     #$06
	jsr     _sscanf
	lda     #<(L0116)
	ldx     #>(L0116)
	jsr     pushax
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$08
	jsr     _cprintf
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$79
	beq     L01DD
	lda     (sp),y
	cmp     #$59
	bne     L011D
L01DD:	lda     #$03
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$04
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
	lda     #$06
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _dectobcd
	jsr     _writertc
L011D:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateConsole (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateConsole: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(L0130)
	ldx     #>(L0130)
	jsr     _cputs
	lda     #<(L0133)
	ldx     #>(L0133)
	jsr     _cputs
	lda     #<(L0136)
	ldx     #>(L0136)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$32
	bne     L013A
	lda     #$21
	jsr     pusha
	lda     #$04
	jsr     _writertc
	lda     #<(L0140)
	ldx     #>(L0140)
	jmp     L01DE
L013A:	lda     #$21
	jsr     pusha
	lda     #$09
	jsr     _writertc
	lda     #<(L0147)
	ldx     #>(L0147)
L01DE:	jsr     _cputs
	lda     #<(L014A)
	ldx     #>(L014A)
	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ UpdateDsky (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDsky: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(L014E)
	ldx     #>(L014E)
	jsr     _cputs
	lda     #<(L0151)
	ldx     #>(L0151)
	jsr     _cputs
	lda     #<(L0154)
	ldx     #>(L0154)
	jsr     _cputs
	lda     #<(L0157)
	ldx     #>(L0157)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	cmp     #$31
	bne     L01E0
	lda     #$22
	jsr     pusha
	lda     #$00
	jsr     _writertc
	lda     #<(L0161)
	ldx     #>(L0161)
	jsr     _cputs
	ldy     #$00
L01E0:	lda     (sp),y
	cmp     #$32
	bne     L01E2
	lda     #$22
	jsr     pusha
	lda     #$01
	jsr     _writertc
	lda     #<(L0169)
	ldx     #>(L0169)
	jsr     _cputs
	ldy     #$00
L01E2:	lda     (sp),y
	cmp     #$33
	bne     L016B
	lda     #$22
	jsr     pusha
	lda     #$02
	jsr     _writertc
	lda     #<(L0171)
	ldx     #>(L0171)
	jsr     _cputs
L016B:	lda     #<(L0174)
	ldx     #>(L0174)
	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ PrintConsoleType (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_PrintConsoleType: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	cmp     #$04
	beq     L017B
	cmp     #$09
	beq     L0180
	jmp     L0184
L017B:	lda     #<(L017D)
	ldx     #>(L017D)
	jmp     L01E3
L0180:	lda     #<(L0182)
	ldx     #>(L0182)
	jmp     L01E3
L0184:	lda     #<(L0186)
	ldx     #>(L0186)
L01E3:	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ PrintDskyType (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_PrintDskyType: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	beq     L018D
	cmp     #$01
	beq     L0192
	cmp     #$02
	beq     L0197
	jmp     L019B
L018D:	lda     #<(L018F)
	ldx     #>(L018F)
	jmp     L01E4
L0192:	lda     #<(L0194)
	ldx     #>(L0194)
	jmp     L01E4
L0197:	lda     #<(L0199)
	ldx     #>(L0199)
	jmp     L01E4
L019B:	lda     #<(L019D)
	ldx     #>(L019D)
L01E4:	jsr     _cputs
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ cgets (__near__ unsigned char *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cgets: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	jsr     decax1
	ldy     #$03
	jsr     staxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L01A5
	eor     #$80
L01A5:	jpl     L01A7
	jmp     L01C7
L01A6:	jsr     _cgetc
	ldy     #$02
	sta     (sp),y
	cmp     #$08
	bne     L01ED
	ldy     #$00
	lda     (sp),y
	beq     L01AC
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
	lda     #$20
	jsr     _cputc
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
L01AC:	ldy     #$02
L01ED:	lda     (sp),y
	cmp     #$20
	bcc     L01BC
	cmp     #$7F
	bcs     L01BC
	ldy     #$08
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
L01BC:	ldy     #$04
	jsr     ldaxysp
	ldy     #$00
	cmp     (sp),y
	bne     L01EC
	txa
	beq     L01EB
L01EC:	ldy     #$02
	lda     (sp),y
	cmp     #$0D
	bne     L01C7
L01EB:	ldy     #$08
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	iny
	sta     (sp),y
L01C7:	ldy     #$01
	lda     (sp),y
	jne     L01A6
L01A7:	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp6
	lda     #$41
	jsr     pusha
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     _cputs
	lda     #$07
	jsr     pusha
	lda     #$00
	jsr     _writertc
	lda     #$08
	jsr     pusha
	lda     #$A5
	jsr     _writertc
	lda     #$00
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$01
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$02
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$03
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$05
	sta     (sp),y
	lda     #$04
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$06
	sta     (sp),y
	tya
	jsr     _readrtc
	jsr     _bcdtodec
	ldy     #$04
	sta     (sp),y
	lda     #$20
	jsr     pusha
	lda     #$A5
	jsr     _writertc
	ldy     #$03
	lda     (sp),y
	cmp     #$0C
	bcc     L01EF
	lda     #$50
	ldy     #$00
	sta     (sp),y
	ldy     #$03
	lda     (sp),y
	cmp     #$0D
	bcc     L01EF
	ldx     #$00
	lda     (sp),y
	ldy     #$0C
	jsr     decaxy
	ldy     #$03
	sta     (sp),y
L01EF:	lda     (sp),y
	bne     L0030
	lda     #$0C
	sta     (sp),y
L0030:	lda     #<(L0035)
	ldx     #>(L0035)
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	lda     (sp),y
	jsr     pusha0
	ldy     #$10
	lda     (sp),y
	jsr     pusha0
	ldy     #$11
	lda     (sp),y
	jsr     pusha0
	ldy     #$12
	lda     (sp),y
	jsr     pusha0
	ldy     #$10
	jsr     _cprintf
	lda     #<(L003F)
	ldx     #>(L003F)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$07
	sta     (sp),y
	lda     #<(L0044)
	ldx     #>(L0044)
	jsr     _cputs
	ldy     #$07
	lda     (sp),y
	cmp     #$79
	beq     L01F0
	cmp     #$59
	bne     L0046
L01F0:	jsr     _UpdateTime
	jsr     _UpdateDate
L0046:	lda     #<(L004E)
	ldx     #>(L004E)
	jsr     _cputs
	lda     #$21
	jsr     _readrtc
	jsr     _PrintConsoleType
	lda     #<(L0054)
	ldx     #>(L0054)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$07
	sta     (sp),y
	lda     #<(L0059)
	ldx     #>(L0059)
	jsr     _cputs
	ldy     #$07
	lda     (sp),y
	cmp     #$79
	beq     L01F1
	cmp     #$59
	bne     L005B
L01F1:	jsr     _UpdateConsole
L005B:	lda     #<(L0062)
	ldx     #>(L0062)
	jsr     _cputs
	lda     #$22
	jsr     _readrtc
	jsr     _PrintDskyType
	lda     #<(L0068)
	ldx     #>(L0068)
	jsr     _cputs
	jsr     _cgetc
	ldy     #$07
	sta     (sp),y
	lda     #<(L006D)
	ldx     #>(L006D)
	jsr     _cputs
	ldy     #$07
	lda     (sp),y
	cmp     #$79
	beq     L01F2
	cmp     #$59
	bne     L006F
L01F2:	jsr     _UpdateDsky
L006F:	lda     #$07
	jsr     pusha
	lda     #$80
	jsr     _writertc
	ldx     #$00
	txa
	jmp     incsp8

.endproc

