;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cputc
	.import		_cputs
	.import		_cprintf
	.import		_cgetc
	.import		_strncpy
	.import		_strtok
	.export		_hdddcb
	.export		_secbuffer
	.export		_parms
	.export		_prtdevice
	.export		_prttable
	.export		_parsecmd
	.export		_getdosmap
	.export		_toupper
	.export		_cgets
	.export		_clearbuff
	.export		_simjumper
	.export		_clearSector
	.export		_main

.segment	"DATA"

_hdddcb:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.segment	"RODATA"

L0071:
	.byte	$20,$20,$20,$20,$20,$20,$20,$2A,$2A,$20,$44,$4F,$4E,$45,$20,$2A
	.byte	$2A,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$0D,$0A,$0D,$0A
	.byte	$00
L0051:
	.byte	$0A,$0D,$20,$43,$6C,$65,$61,$72,$69,$6E,$67,$20,$73,$65,$63,$74
	.byte	$6F,$72,$73,$20,$31,$2D,$25,$75,$20,$6F,$6E,$20,$74,$72,$61,$63
	.byte	$6B,$73,$20,$25,$75,$2D,$25,$75,$0A,$0D,$00
L0014:
	.byte	$0A,$0D,$20,$43,$48,$4F,$4F,$53,$45,$20,$44,$52,$49,$56,$45,$20
	.byte	$54,$4F,$20,$50,$52,$45,$50,$20,$46,$4F,$52,$20,$44,$4F,$53,$2F
	.byte	$36,$35,$3A,$00
L0049:
	.byte	$20,$20,$20,$20,$4D,$61,$78,$20,$64,$69,$72,$65,$63,$74,$6F,$72
	.byte	$79,$20,$65,$6E,$74,$72,$69,$65,$73,$3A,$20,$25,$75,$0A,$0D,$00
L0068:
	.byte	$20,$43,$6C,$65,$61,$72,$69,$6E,$67,$20,$73,$65,$63,$74,$6F,$72
	.byte	$73,$20,$25,$75,$3A,$25,$75,$20,$20,$20,$20,$20,$20,$20,$0D,$00
L00C3:
	.byte	$0A,$0D,$20,$44,$4F,$53,$2F,$36,$35,$20,$44,$72,$69,$76,$65,$20
	.byte	$61,$73,$73,$69,$67,$6E,$6D,$65,$6E,$74,$3A,$0A,$0D,$00
L003C:
	.byte	$20,$20,$20,$20,$53,$65,$63,$74,$6F,$72,$73,$20,$70,$65,$72,$20
	.byte	$74,$72,$61,$63,$6B,$3A,$20,$25,$75,$0A,$0D,$00
L0030:
	.byte	$0A,$0D,$0A,$0D,$20,$50,$72,$65,$70,$70,$69,$6E,$67,$20,$64,$72
	.byte	$69,$76,$65,$20,$25,$63,$3A,$0A,$0D,$00
L0040:
	.byte	$20,$20,$20,$20,$53,$79,$73,$74,$65,$6D,$20,$74,$72,$61,$63,$6B
	.byte	$73,$3A,$20,$25,$75,$0A,$0D,$00
L0035:
	.byte	$20,$20,$20,$20,$4D,$61,$78,$20,$62,$6C,$6F,$63,$6B,$73,$3A,$20
	.byte	$25,$75,$0A,$0D,$00
L0044:
	.byte	$20,$20,$20,$20,$42,$6C,$6F,$63,$6B,$20,$73,$69,$7A,$65,$3A,$20
	.byte	$25,$75,$0A,$0D,$00
L00F4:
	.byte	$55,$4E,$4B,$4E,$4F,$57,$4E,$00
L00CF:
	.byte	$20,$20,$25,$63,$3A,$3D,$00
L00F0:
	.byte	$50,$50,$49,$44,$45,$00
L00D6:
	.byte	$3A,$25,$69,$0A,$0D,$00
L00E6:
	.byte	$55,$53,$42,$00
L00F7:
	.byte	$25,$69,$00
L00EB:
	.byte	$46,$44,$00
L00E1:
	.byte	$53,$44,$00
L00A7	:=	L00CF+5
L0098:
	.byte	$20,$00
L0093	:=	L0098+0
L008E	:=	L0098+0
L00B5	:=	L00CF+5

.segment	"BSS"

_secbuffer:
	.res	129,$00
_parms:
	.res	5,$00

; ---------------------------------------------------------------
; void __near__ prtdevice (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_prtdevice: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	and     #$F0
	beq     L00DF
	cmp     #$10
	beq     L00E4
	cmp     #$20
	beq     L00E9
	cmp     #$30
	beq     L00EE
	jmp     L00F2
L00DF:	lda     #<(L00E1)
	ldx     #>(L00E1)
	jsr     _cputs
	jmp     L00DD
L00E4:	lda     #<(L00E6)
	ldx     #>(L00E6)
	jsr     _cputs
	jmp     incsp1
L00E9:	lda     #<(L00EB)
	ldx     #>(L00EB)
	jsr     _cputs
	jmp     L00DD
L00EE:	lda     #<(L00F0)
	ldx     #>(L00F0)
	jsr     _cputs
	jmp     L00DD
L00F2:	lda     #<(L00F4)
	ldx     #>(L00F4)
	jsr     _cputs
	jmp     incsp1
L00DD:	lda     #<(L00F7)
	ldx     #>(L00F7)
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	and     #$0F
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ prttable (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_prttable: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	lda     #<(L00C3)
	ldx     #>(L00C3)
	jsr     _cputs
	ldx     #$00
	txa
L019A:	jsr     stax0sp
	cmp     #$10
	txa
	sbc     #$00
	bvc     L00CC
	eor     #$80
L00CC:	bpl     L00C6
	lda     #<(L00CF)
	ldx     #>(L00CF)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     asrax1
	ldy     #$41
	jsr     incaxy
	jsr     pushax
	ldy     #$04
	jsr     _cprintf
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _prtdevice
	lda     #<(L00D6)
	ldx     #>(L00D6)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	clc
	ldy     #$04
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
	jsr     ldax0sp
	jsr     incax1
	jmp     L019A
L00C6:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ parsecmd (__near__ unsigned char *, __near__ unsigned char *, __near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parsecmd: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	ldy     #$09
	jsr     ldaxysp
	jsr     decax1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	jsr     decsp4
	ldy     #$0C
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldy     #$04
	lda     (sp),y
	cmp     #$80
	bcc     L0084
	lda     #$7F
	sta     (sp),y
L0084:	lda     (sp),y
	clc
	ldy     #$0D
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldy     #$10
	jsr     pushwysp
	lda     #<(L008E)
	ldx     #>(L008E)
	jsr     _strtok
	ldy     #$02
	jsr     staxysp
	jsr     push0
	lda     #<(L0093)
	ldx     #>(L0093)
	jsr     _strtok
	ldy     #$02
	jsr     staxysp
	jsr     push0
	lda     #<(L0098)
	ldx     #>(L0098)
	jsr     _strtok
	jsr     stax0sp
	cpx     #$00
	bne     L019B
	cmp     #$00
	beq     L009A
L019B:	ldy     #$0A
	jsr     pushwysp
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	lda     #$05
	jsr     _strncpy
L009A:	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L00B7
	ldy     #$05
	jsr     pushwysp
	lda     #<(L00A7)
	ldx     #>(L00A7)
	jsr     _strtok
	ldy     #$02
	jsr     staxysp
	cpx     #$00
	bne     L019C
	cmp     #$00
	beq     L00B7
L019C:	ldy     #$0E
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldx     #$00
	lda     #$1D
	jsr     _strncpy
	ldx     #$00
	lda     #$01
	ldy     #$05
	jsr     staxysp
	jsr     push0
	lda     #<(L00B5)
	ldx     #>(L00B5)
	jsr     _strtok
	ldy     #$02
	jsr     staxysp
	cpx     #$00
	bne     L019D
	cmp     #$00
	beq     L00B7
L019D:	ldy     #$0C
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldx     #$00
	lda     #$1D
	jsr     _strncpy
	ldx     #$00
	lda     #$02
	ldy     #$05
	jsr     staxysp
L00B7:	ldy     #$06
	jsr     ldaxysp
	ldy     #$0F
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ getdosmap (unsigned char, unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getdosmap: near

.segment	"CODE"

	jsr     pushax
	lda     $002C
	ldx     $002C+1
	jsr     pushax
	jsr     pushw0sp
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosumula0
	jsr     tosaddax
	jsr     pushax
	jsr     decsp2
	ldx     #$00
	txa
L019F:	jsr     stax0sp
	cmp     #$09
	txa
	sbc     #$00
	bvc     L0114
	eor     #$80
L0114:	bpl     L010E
	jsr     ldax0sp
	clc
	ldy     #$06
	adc     (sp),y
	sta     sreg
	txa
	iny
	adc     (sp),y
	sta     sreg+1
	jsr     ldax0sp
	clc
	ldy     #$02
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
	jsr     ldax0sp
	jsr     incax1
	jmp     L019F
L010E:	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ toupper (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_toupper: near

.segment	"CODE"

	jsr     pushax
	jmp     L00FD
L00FB:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$61
	bcc     L00FF
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$7B
	bcs     L00FF
	jsr     ldax0sp
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	and     #$5F
	sta     (sreg),y
L00FF:	jsr     ldax0sp
	jsr     incax1
	jsr     stax0sp
L00FD:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L00FB
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ cgets (__near__ unsigned char *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cgets: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	jsr     decax1
	ldy     #$03
	jsr     staxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0120
	eor     #$80
L0120:	jpl     L0122
	jmp     L0142
L0121:	jsr     _cgetc
	ldy     #$02
	sta     (sp),y
	cmp     #$08
	bne     L01AB
	ldy     #$00
	lda     (sp),y
	beq     L0127
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
	lda     #$20
	jsr     _cputc
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
L0127:	ldy     #$02
L01AB:	lda     (sp),y
	cmp     #$20
	bcc     L0137
	cmp     #$7F
	bcs     L0137
	ldy     #$08
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	ldy     #$02
	lda     (sp),y
	jsr     _cputc
L0137:	ldy     #$04
	jsr     ldaxysp
	ldy     #$00
	cmp     (sp),y
	bne     L01AA
	txa
	beq     L01A9
L01AA:	ldy     #$02
	lda     (sp),y
	cmp     #$0D
	bne     L0142
L01A9:	ldy     #$08
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	iny
	sta     (sp),y
L0142:	ldy     #$01
	lda     (sp),y
	jne     L0121
L0122:	ldx     #$00
	lda     (sp,x)
	clc
	ldy     #$05
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	txa
	tay
	sta     (ptr1),y
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ clearbuff (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clearbuff: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	txa
L01AD:	jsr     stax0sp
	cmp     #$80
	txa
	sbc     #$00
	bvc     L0157
	eor     #$80
L0157:	bpl     L0151
	lda     #<(_secbuffer)
	ldy     #$00
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(_secbuffer)
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$E5
	dey
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	jmp     L01AD
L0151:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ simjumper (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_simjumper: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	lda     $0101
	ldx     $0101+1
	jsr     pushax
	lda     #$4A
	jsr     pusha0
	lda     #$4B
	jsr     pusha0
	ldy     #$0A
	lda     (sp),y
	sta     _parms
	dey
	lda     (sp),y
	sta     _parms+1
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$08
	adc     (sp),y
	bcc     L01AE
	inx
L01AE:	jsr     decax3
	ldy     #$06
	jsr     staxysp
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$4C
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
	jsr     pushw0sp
	ldy     #$09
	jsr     ldaxysp
	ldy     #$00
	jsr     staxspidx
	lda     _parms
	ldy     _parms+1
	jsr     $004A
	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ clearSector (unsigned char, unsigned int, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clearSector: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	lda     #<(_secbuffer)
	ldx     #>(_secbuffer)
	jsr     pushax
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$1B
	jsr     _simjumper
	ldy     #$06
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$1E
	jsr     _simjumper
	ldy     #$04
	lda     (sp),y
	dey
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$21
	jsr     _simjumper
	ldy     #$00
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	ldy     #$01
	lda     (sp),y
	iny
	sta     (sp),y
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$24
	jsr     _simjumper
	lda     #$00
	jsr     pusha
	jsr     pusha
	lda     #$2A
	jsr     _simjumper
	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     $002E
	ldx     $002E+1
	jsr     pushax
	ldy     #$5D
	jsr     subysp
	ldy     #$5E
	jsr     ldaxysp
	jsr     _prttable
	lda     #<(L0014)
	ldx     #>(L0014)
	jsr     _cputs
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldx     #$00
	lda     #$4F
	jsr     _cgets
	ldy     #$00
	lda     (sp),y
	ldx     #$00
	and     #$5F
	ldy     #$41
	jsr     decaxy
	ldy     #$50
	sta     (sp),y
	jsr     pusha
	lda     #<(_hdddcb)
	ldx     #>(_hdddcb)
	jsr     _getdosmap
	ldx     _hdddcb+3
	lda     #$00
	clc
	adc     _hdddcb+2
	bcc     L01AF
	inx
L01AF:	ldy     #$57
	jsr     staxysp
	ldx     _hdddcb+5
	lda     #$00
	clc
	adc     _hdddcb+4
	bcc     L01B0
	inx
L01B0:	ldy     #$5B
	jsr     staxysp
	ldx     _hdddcb+8
	lda     #$00
	clc
	adc     _hdddcb+7
	bcc     L01B1
	inx
L01B1:	jsr     incax1
	ldy     #$55
	jsr     staxysp
	lda     #<(L0030)
	ldx     #>(L0030)
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
	lda     #<(L0035)
	ldx     #>(L0035)
	jsr     pushax
	ldx     _hdddcb+1
	lda     #$00
	clc
	adc     _hdddcb
	bcc     L01B2
	inx
L01B2:	jsr     pushax
	ldy     #$04
	jsr     _cprintf
	lda     #<(L003C)
	ldx     #>(L003C)
	jsr     pushax
	ldy     #$5C
	jsr     pushwysp
	ldy     #$04
	jsr     _cprintf
	lda     #<(L0040)
	ldx     #>(L0040)
	jsr     pushax
	ldy     #$60
	jsr     pushwysp
	ldy     #$04
	jsr     _cprintf
	lda     #<(L0044)
	ldx     #>(L0044)
	jsr     pushax
	lda     _hdddcb+6
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
	lda     #<(L0049)
	ldx     #>(L0049)
	jsr     pushax
	ldy     #$5A
	jsr     pushwysp
	ldy     #$04
	jsr     _cprintf
	ldy     #$5E
	jsr     pushwysp
	ldy     #$58
	jsr     ldaxysp
	jsr     shrax2
	jsr     pushax
	ldy     #$5C
	jsr     ldaxysp
	jsr     tosudivax
	jsr     tosaddax
	jsr     decax1
	ldy     #$59
	jsr     staxysp
	lda     #<(L0051)
	ldx     #>(L0051)
	jsr     pushax
	ldy     #$5C
	jsr     pushwysp
	ldy     #$62
	jsr     pushwysp
	ldy     #$62
	jsr     pushwysp
	ldy     #$08
	jsr     _cprintf
	jsr     _clearbuff
	ldy     #$5C
	jsr     ldaxysp
L01B6:	ldy     #$53
	jsr     staxysp
	sec
	ldy     #$59
	sbc     (sp),y
	sta     tmp1
	txa
	iny
	sbc     (sp),y
	ora     tmp1
	bcc     L005A
	bne     L0058
L005A:	ldx     #$00
	lda     #$01
L01B5:	ldy     #$51
	jsr     staxysp
	sec
	ldy     #$57
	sbc     (sp),y
	sta     tmp1
	txa
	iny
	sbc     (sp),y
	ora     tmp1
	bcc     L0062
	bne     L0059
L0062:	lda     #<(L0068)
	ldx     #>(L0068)
	jsr     pushax
	ldy     #$58
	jsr     pushwysp
	ldy     #$58
	jsr     pushwysp
	ldy     #$06
	jsr     _cprintf
	ldy     #$50
	lda     (sp),y
	jsr     pusha
	ldy     #$57
	jsr     pushwysp
	ldy     #$55
	jsr     ldaxysp
	jsr     _clearSector
	ldy     #$52
	jsr     ldaxysp
	jsr     incax1
	jmp     L01B5
L0059:	ldy     #$54
	jsr     ldaxysp
	jsr     incax1
	jmp     L01B6
L0058:	lda     #<(L0071)
	ldx     #>(L0071)
	jsr     pushax
	ldy     #$58
	jsr     pushwysp
	ldy     #$58
	jsr     pushwysp
	ldy     #$06
	jsr     _cprintf
	ldx     #$00
	txa
	ldy     #$5F
	jmp     addysp

.endproc

